# _config.yml
title: P-Tub 
author: Sagar Dash 
baseurl: "" 
exclude: # things to exclude from the build process
  - README.md
  - .ruby-version
  - Gemfile
  - Gemfile.lock

... other config ...
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-angular
